# Generated by Django 3.1 on 2020-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiedb_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
