# Generated by Django 3.1 on 2020-08-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indiedb_games', '0003_gameimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image', serialize=False, to='indiedb_games.game'),
        ),
    ]
