# Generated by Django 3.1 on 2020-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiedb_games', '0004_auto_20200821_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
